// Fictional chats for demo mode (screenshots and videos). Every name, place and
// number is made up; phone numbers use the 555-0100–0199 range reserved for
// fiction. Times are clock times on a fixed demo day so captures look the same
// on every launch: "today" ends at 09:41. Pictures and the voice note are
// generated by scripts/generate-demo-media.mjs (abstract shapes and tones).

import avatarBikes from './assets/avatar-bikes.webp';
import avatarHike from './assets/avatar-hike.webp';
import avatarLibrary from './assets/avatar-library.webp';
import avatarMaya from './assets/avatar-maya.webp';
import avatarSam from './assets/avatar-sam.webp';
import photoSketch from './assets/photo-sketch.webp';
import photoTrailMap from './assets/photo-trail-map.webp';
import voiceNote from './assets/voice-note.ogg';
import type {AllowedReactions, MessageContent, ReactionSummary, RecentReaction} from '../telegram/model';

export type DemoMedia = {url: string; mimetype: string};

export type DemoMessage = {
  id: string;
  fromMe: boolean;
  senderName: string | null;
  /** Days before the demo day (0 = today). */
  daysAgo: number;
  /** Local clock time, `HH:MM`. */
  time: string;
  content: MessageContent;
  reactions?: ReactionSummary[];
  recentReaction?: RecentReaction;
  /** Photo or voice note returned by getMedia. */
  media?: DemoMedia;
};

export type DemoChat = {
  id: string;
  /** Contact, group or channel name; omitted for a number that is not in the contacts. */
  name?: string;
  phone?: string;
  isGroup: boolean;
  unreadCount: number;
  messages: DemoMessage[];
  avatar?: string;
  /** Reactions the chat accepts; private chats take the standard set. */
  allowed?: AllowedReactions;
  /** Answer that arrives once, a few seconds after the first reply sent in this chat. */
  autoReply?: string;
};

/** Clock time of the newest demo message. */
export const DEMO_DAY_END = '09:41';

/**
 * Telegram's standard (free) emoji reactions as the demo knows them; like the
 * real set it has 🤣 and 😁 but not 😂, so the menu shows the substitute.
 */
export const DEMO_STANDARD_REACTIONS = [
  '👍', '👎', '❤', '🔥', '🥰', '👏', '😁', '🤔', '🤯', '😱', '😢', '🎉', '🤩', '🙏', '👌',
  '😍', '💯', '🤣', '⚡', '🏆', '💔', '🤨', '😐', '😴', '😭', '🤓', '👀', '🙈', '😇', '🤝', '🤗', '😎',
];

const VOICE_SECONDS = 6;

const text = (value: string): MessageContent => ({kind: 'text', text: value});

let counter = 0;
function message(
  fromMe: boolean,
  daysAgo: number,
  time: string,
  content: MessageContent,
  senderName: string | null = null,
  extra: Partial<DemoMessage> = {},
): DemoMessage {
  counter += 1;
  return {id: String(1000 + counter), fromMe, senderName: fromMe ? null : senderName, daysAgo, time, content, ...extra};
}

const me = (daysAgo: number, time: string, content: MessageContent, extra: Partial<DemoMessage> = {}) =>
  message(true, daysAgo, time, content, null, extra);
const photo = (caption: string, url: string): Partial<DemoMessage> & {content: MessageContent} => ({
  content: {kind: 'photo', text: caption},
  media: {url, mimetype: 'image/webp'},
});
const voice = (): Partial<DemoMessage> & {content: MessageContent} => ({
  content: {kind: 'audio', text: '', seconds: VOICE_SECONDS},
  media: {url: voiceNote, mimetype: 'audio/ogg'},
});

/** A fresh copy of the demo chats. */
export function demoChats(): DemoChat[] {
  counter = 0;
  const sketch = photo('Sketch from Monday', photoSketch);
  const trail = photo('Trail map', photoTrailMap);
  const mayaVoice = voice();
  const samVoice = voice();
  return [
    {
      id: '7700101',
      name: 'Maya Chen',
      isGroup: false,
      unreadCount: 2,
      avatar: avatarMaya,
      autoReply: 'Perfect, thanks! See you at 10.',
      messages: [
        message(false, 0, '09:16', text('Morning! Are we still on for the design review?'), 'Maya Chen'),
        me(0, '09:18', text('Yes, 10:00 in Room 3.'), {reactions: [{emoji: '👍', count: 1, mine: false}]}),
        me(0, '09:18', text("I'll share the slides before then.")),
        message(false, 0, '09:24', sketch.content, 'Maya Chen', {media: sketch.media}),
        message(false, 0, '09:31', mayaVoice.content, 'Maya Chen', {media: mayaVoice.media}),
        message(false, 0, '09:40', text('Great, see you there.'), 'Maya Chen'),
        message(false, 0, DEMO_DAY_END, text('Can you bring the projector?'), 'Maya Chen'),
      ],
    },
    {
      id: '-4000042',
      name: 'Hike Crew',
      isGroup: true,
      unreadCount: 2,
      avatar: avatarHike,
      allowed: {kind: 'some', emojis: ['👍', '❤', '🤣', '😢', '🔥', '🎉']},
      messages: [
        message(false, 0, '08:02', text("Who's in for Saturday?"), 'Ana Ruiz'),
        message(false, 0, '08:05', text('Me! Leaving at 7.'), 'Leo Park', {
          reactions: [
            {emoji: '👍', count: 2, mine: false},
            {emoji: '❤', count: 1, mine: true},
          ],
        }),
        me(0, '08:07', text('Count me in.')),
        message(false, 0, '08:30', text("Same. I'll bring snacks."), 'Priya Nair'),
        message(false, 0, '09:28', trail.content, 'Leo Park', {media: trail.media}),
      ],
    },
    {
      id: '7700102',
      name: 'Sam Rivera',
      isGroup: false,
      unreadCount: 0,
      avatar: avatarSam,
      autoReply: 'Great, I booked a table.',
      messages: [
        message(false, 1, '21:02', samVoice.content, 'Sam Rivera', {media: samVoice.media}),
        message(false, 0, '08:10', text('Dinner tonight?'), 'Sam Rivera'),
        me(0, '08:15', text('Sounds good, 7 pm works.'), {
          reactions: [{emoji: '❤', count: 1, mine: false}],
          recentReaction: {emoji: '❤', senderName: 'Sam Rivera', unread: true},
        }),
      ],
    },
    {
      id: '-1001000000042',
      name: 'Library News',
      isGroup: false,
      unreadCount: 1,
      avatar: avatarLibrary,
      allowed: {kind: 'none'},
      messages: [
        message(false, 1, '10:00', text('Opening hours change on Monday: 8 am to 8 pm.'), 'Library News'),
        message(false, 0, '07:30', {kind: 'poll', text: 'Best reading spot?'}, 'Library News'),
      ],
    },
    {
      id: '7700107',
      name: 'Bike Shop',
      isGroup: false,
      unreadCount: 0,
      avatar: avatarBikes,
      messages: [
        message(false, 1, '18:12', text('Your bike is ready for pickup.'), 'Bike Shop'),
        message(false, 1, '18:20', {kind: 'document', text: 'Invoice_0042.pdf'}, 'Bike Shop'),
      ],
    },
    {
      id: '7700103',
      name: 'Jordan Lee',
      isGroup: false,
      unreadCount: 0,
      messages: [
        me(3, '19:40', text('Where should we meet?')),
        message(false, 3, '19:45', {kind: 'location', text: 'Central Station'}, 'Jordan Lee'),
      ],
    },
    {
      id: '7700199',
      phone: '+12025550199',
      isGroup: false,
      unreadCount: 1,
      messages: [message(false, 9, '14:05', text('Hi! Is the desk still available?'))],
    },
  ];
}
